
services:
  mariadb:
    build: ${BUILD_PATH}/mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: always
    networks:
      - docker-network
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    depends_on:
      - mariadb
    build: ${BUILD_PATH}/wordpress
    container_name: wordpress
    env_file:
      - .env
    restart: always
    ports:
      - "9000:9000"
    networks:
      - docker-network
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    depends_on:
      - wordpress
    build: ${BUILD_PATH}/nginx
    container_name: nginx
    env_file:
      - .env
    restart: always
    networks:
      - docker-network
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"

  portainer:
    build: ${BUILD_PATH_BONUS}/portainer
    container_name: portainer
    env_file:
      - .env
    restart: always
    networks:
      - docker-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "1312:9000"

networks:
  docker-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pjaguin/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pjaguin/data/wordpress
      o: bind
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pjaguin/data/portainer
      o: bind
