
services:
  mariadb:
    build: ${BUILD_PATH}/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - docker-network
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build: ${BUILD_PATH}/wordpress
    container_name: wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - docker-network
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  nginx:
    depends_on:
      - wordpress
    build: ${BUILD_PATH}/nginx
    container_name: nginx
    env_file:
      - .env
    networks:
      - docker-network
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    restart: always

  portainer:
    build: ${BUILD_PATH_BONUS}/portainer
    container_name: portainer
    env_file:
      - .env
    networks:
      - docker-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "1312:9000"
    restart: always

  ftp:
    build: ${BUILD_PATH_BONUS}/ftp
    container_name: ftp
    env_file:
      - .env
    networks:
      - docker-network
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/home/$FTP_USER/ftp/wordpress
    ports:
      - "21:21"
      - "20:20"
      - "40000-40001:40000-40001"
    restart: always

  hannah_montana:
    build: ${BUILD_PATH_BONUS}/hannah_montana
    container_name: hannah_montana
    env_file:
      - .env
    networks:
      - docker-network 
    ports:
      - "1311:1311"
    volumes:
      - hannah_montana_data:/var/www/html
    restart: always

  redis:
    build: ${BUILD_PATH_BONUS}/redis
    container_name: redis
    depends_on:
      - wordpress
    networks:
      - docker-network
    volumes:
      - wordpress_data:/var/www/html/
    ports:
      - "6379:6379"
    restart: always

  adminer:
    build: ${BUILD_PATH_BONUS}/adminer
    container_name: adminer
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - docker-network
    ports:
      - "1313:1313"
    restart: always

networks:
  docker-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pjaguin/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pjaguin/data/wordpress
      o: bind
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pjaguin/data/portainer
      o: bind
  hannah_montana_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pjaguin/data/hannah_montana
      o: bind
