services:
  mariadb:/data/pjaguin/
/data/pjaguin/
/data/pjaguin/
    build: ${BUILD_PATH}/mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: always
    networks:
      - docker-network
    volumes:
      - mariadb_data:/var/lib/mysql
  wordpress:
    build: ${BUILD_PATH}/wordpress
    container_name: wordpress
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress_data:/var/www/html
  portainer:
    build: ${BUILD_PATH_BONUS}/portainer
    container_name: portainer
    env_file:
      - .env
    restart: always
    networks:
      - docker-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "1312:9000"

networks:
  docker-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pjaguin/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pjaguin/data/wordpress
      o: bind
  nginx_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pjaguin/data/nginx
      o: bind
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pjaguin/data/portainer
      o: bind
